### ISSUE TITLE
Supported for VSCode ?

### ISSUE THREAD

**Issue by trgkyle** [rlue/vim-barbaric#17]
I need to add vim-barbaric integrate to vscode(Editor) that using vim inside, how can I do this ?

**Comment by rlue** [comment]
I think the only way to do this would be to rewrite barbaric in TypeScript.

I don't use VSCode, so I'm not 100% sure how its so-called "vim emulation" works. From what I can see, vscodevim.vim only provides [a limited set of emulated plugins](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim#emulated-plugins). Looking more closely at the source code on GitHub, [it appears that they've re-implemented this small set of popular plugins in TS](https://github.com/VSCodeVim/Vim/tree/9e50e0dc5225ad131e51dbf699a665c5cafe5135/src/actions/plugins), rather than building a viml engine to actually emulate support for existing vim plugins.

This issue belongs on the vscodevim/vim repo, not here (although I highly doubt it will get much traction there).

Barbaric is a small/lightweight plugin, though, so you might try porting it to TS yourself!

**Comment by yunyuyuan** [comment]
You can use [vscode-nvim](https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim), it works fine with all nvim features,also it can use vim-plug!
