### ISSUE TITLE
A question not about this plugin.

### ISSUE THREAD

**Issue by zx1986** [rlue/vim-barbaric#21]
Sorry about this issue post.
I just wonder have you seem that IME name keep showing when you switch input method in vim?
And how to disable it?

For example, when I want to type something in Chinese, I do ctrl + space to switch input method (to macOS pinyin input method),
vim will show an pop-up block (something like auto-completion dropdown menu) write in "zh-Hans",
if I switch back to English input method, vim will show a block write in "en".
This is very annoying for me ....

And my airline with powerlineish theme had IME name after filename field too.

Do you have any key word or some cules about this? I googling this for a long time ......

**Comment by rlue** [comment]
Are you sure that the IME status hint ("popup block") is being shown by vim, and not by macOS? I'm on Linux, so I can't confirm this for you, but here's something you can try:

1. Open any other macOS application with a text input field (_e.g.,_ your browser, or TextEdit, or Mail).
2. Use ctrl-space to switch input methods. 

Does the popup block still appear? If so, the problem is with macOS and not with vim or vim-barbaric.

AFAIK this is pretty standard behavior for a desktop IME, and I would bet that it cannot be disabled.

**Comment by zx1986** [comment]
I am pretty sure that "popup block" is in vim (I am using neovim).
And I found that effect come from "coc" plugin!

I am still finding how & where that effect setting, and try to disable it.
I will open an issue(or question) in https://github.com/neoclide/coc.nvim/issues

Thanks!

**Comment by zx1986** [comment]
I found it! 
the bug is from a coc plugin: https://github.com/neoclide/coc-imselect

I remove this plugin and it fixed!
thank god ...
