### ISSUE TITLE
ibus engine print extra color format

### ISSUE THREAD

**Issue by yslan** [rlue/vim-barbaric#23]
### Issue
When opening a file, it will print this every time:
```
^[[2;2R^[[3;2R^[[>0;115;0c^[]10;rgb:fcfc/fcfc/fcfc^G^[]11;rgb:2323/2626/2727^G
```
It looks like some color format is printed into stderr or stdout and it will disapear after redraw the screen (`ctrl+l`)

### Possible resaon
I manage to trace it down. The source comes from `ibus engine` at here:
https://github.com/rlue/vim-barbaric/blob/bb4bef87417fc3ad92319f556f02d6658b401288/autoload/barbaric.vim#L56

I also notice that if you execute ibus from other users, says `sudo ibus engine`, it will create this error message with some colors.
```
(process:1842822): IBUS-CRITICAL **: 12:31:28.219: ibus_bus_get_global_engine: assertion 'IBUS_IS_BUS (bus)' failed
No engine is set.
```
Therefore, my guess is, there is some warning message from ibus which only shown in vim but not from the terminal.

### Workaround
Commenting out the VimEnter line to avoid the first ibus engine call works.
And everything works so I'm happy with this so far.

https://github.com/rlue/vim-barbaric/blob/bb4bef87417fc3ad92319f556f02d6658b401288/plugin/barbaric.vim#L65

**Comment by rlue** [comment]
Hi, very sorry for the extreme delay on responding to this bug report.

Great catch. Unfortunately, I do not use ibus, so it would be a lot of work for me to debug this issue.

What happens when you run `ibus engine` from the vim command line (_i.e.,_ with `:!ibus engine` in normal mode)? Do you get the same error? Does the error happen when you run the same command from the shell?

If you get the error in vim but not in the shell, it sounds like there is some difference between your shell environment and vim's. If you _don't_ get the error in vim, well then I'm very confused.

**Comment by yslan** [comment]
Thanks for the reply!

Running `ibus engine` from vim doesn't give any error.   I also confirm that vim uses the same shell as my terminal via `:!echo $SHELL`

This only happens at the `VimEnter`. The `InsertLeave` doesn't have the error even though it's calling the same thing
`  autocmd InsertLeave * call barbaric#switch('normal')`

---
ok. New finding. This is probably not an ibus issue. This happens at the very first system call. I will have same error if I do this
```
  elseif g:barbaric_ime == 'ibus'
    call system('ls -ltra ')
"    return system('ibus engine;echo $SHELL;whoami')
  endif
```
And, a trick to get rid of this is have a silent dummy call like this 
```
  elseif g:barbaric_ime == 'ibus'
    silent call system('ls -ltra ')
    return system('ibus engine;echo $SHELL;whoami')
  endif
```
---

I'm very new to vimrc and not quite sure how it works. 
Is it normal not seeing any printing message from `call system('ls -ltra')`?
How to print things into terminal?

**Comment by rlue** [comment]
> Is it normal not seeing any printing message from call system('ls -ltra')?

Yep! From `:help :call` (emphasis mine):

> `:[range]cal[l] {name}([arguments])`
>
> Call a function.  The name of the function and its arguments
> are as specified with `:function`.  Up to 20 arguments can be
> used.  **The returned value is discarded.**

---

> How to print things into terminal?

To print it to the screen, use `:!ls -ltra`. To write it into the buffer, use `:read !ls -ltra` (or `!!ls -ltra`).

---

In any case, I wish I had a better solution for your issue! Unfortunately, I don't know enough to understand where your error is coming from. :\\

Going to close this issue since it looks like it's originating from elsewhere, but feel free to open it again if you find out more.
